version: '3.3'
services:
  lamppnginxloadbalance:
    image: nginx
    restart: always
    container_name: nginx
    volumes:
      - ./loadbalance/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '7000:80'
      - '7443:443'
      - '7025:22'
    networks:
      - lampp
    depends_on:
      - web1
      - web2
      - web3
      
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: lampp
      MYSQL_DATABASE: lampp
      MYSQL_USER: lampp
      MYSQL_PASSWORD: lampp
    volumes:
      - ./mariadb_data:/var/lib/mysql
    networks:
      - lampp
    ports:
      - '7070:80'
      - '7743:443'
      - '7010:22'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      MYSQL_ROOT_USER: lampp
      MYSQL_ROOT_PASSWORD: lampp
    ports:
      - "8181:80"
    depends_on:
      - mariadb
    networks:
      - lampp

 web1:
    image: php:7.4-apache
    container_name: web1
    restart: always
    ports:
      - "7001:80"
      - '7021:22'
    volumes:
      - ./web:/var/www/html
    depends_on:
      - mariadb
    networks:
      - lampp

  web2:
    image: php:7.4-apache
    container_name: web2
    restart: always
    ports:
      - "7002:80"
      - '7022:22'
    volumes:
      - ./web:/var/www/html
    depends_on:
      - mariadb
    networks:
      - lampp


  web3:
    image: php:7.4-apache
    container_name: web3
    restart: always
    ports:
      - "7003:80"
      - '7023:22'
    volumes:
      - ./web:/var/www/html
    depends_on:
      - mariadb
    networks:
      - lampp


networks:
  lampp:
    driver: bridge
